### PR TITLE
Fix building on OS X, closes #141

### LINKED ISSUE #141: Can not build on Mac OS X Yosemite (10.10.1)
PHP 5.6
librabbitmq 0.5.2 (downloaded from github)
php-amqp 1.6.0 beta2 (From pecl.php.net or from github)

~~~
phpize .
./configure
make
~~~

then error occurs:

~~~
duplicate symbol _le_amqp_connection_resource_persistent in:
    .libs/amqp.o
    .libs/amqp_connection.o
duplicate symbol _le_amqp_connection_resource in:
    .libs/amqp.o
    .libs/amqp_connection.o
duplicate symbol _le_amqp_connection_resource in:
    .libs/amqp.o
    .libs/amqp_connection_resource.o
duplicate symbol _le_amqp_connection_resource_persistent in:
    .libs/amqp.o
    .libs/amqp_connection_resource.o
duplicate symbol _le_amqp_connection_resource in:
    .libs/amqp.o
    .libs/amqp_channel.o
duplicate symbol _le_amqp_connection_resource_persistent in:
    .libs/amqp.o
    .libs/amqp_channel.o
ld: 6 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [amqp.la] Error 1
~~~

### PR DESCRIPTION
**Pull request by pinepain**

### CODE REVIEW

**Comment by lstrojny** [comment]
Can you squash and add a changelog entry?

**Comment by pinepain** [comment]
Sure. beta3?

**Comment by pinepain** [comment]
@lstrojny JFYI: beta1 tag is not tagged, so comparison with it fails (check it - https://github.com/pdezwart/php-amqp/compare/v1.4.0...v1.6.0beta1)

**Comment by lstrojny** [comment]
Perfect, thank you!
