### PR TITLE
fix build with librabbitmq 0.5, fix #177

### LINKED ISSUE #177: Failed build with librabbitmq 0.5
1.6.0beta3 build fine with librabbitmq 0.5.x (available in EPEL for RHEL and CentOS, can't be upgrade because of ABI break)

Buildtime:

    /builddir/build/BUILD/more-php56-php-pecl-amqp-1.6.0/NTS/amqp_connection.c:146: warning: implicit declaration of function 'amqp_get_frame_max'
    /builddir/build/BUILD/more-php56-php-pecl-amqp-1.6.0/NTS/amqp_connection.c:154: warning: implicit declaration of function 'amqp_get_heartbeat'

Runtime:

     PHP Warning:  PHP Startup: Unable to load dynamic library 'NTS/modules/amqp.so' - NTS/modules/amqp.so: undefined symbol: amqp_get_heartbeat in Unknown on line 0

It will be nice to have this feature conditional.
If not possible, to check (in config.m4) with a message explaining minimal version required.

### PR DESCRIPTION
**Pull request by remicollet**
Seems simple, so probably worth to allow.

Notice: this commit also add missing reflection for getHeartbeatInterval and getMaxFrameSize (when available)

### CODE REVIEW

**Comment by remicollet** [comment]
FYI, build.log against  librabbitmq, RHEL-7 + EPEL
https://copr-be.cloud.fedoraproject.org/results/remi/php56more/epel-7-x86_64/00116516-php-pecl-amqp/build.log.gz

**Comment by lstrojny** [comment]
Thanks!

**Comment by hanikesn** [comment]
The TravisCI file should probably also be updated, to test it with rabbitmq-0.5.2

**Comment by pinepain** [comment]
0.5.2 is pretty old. I hope we are not going to tests php-amqp against all existent rabbitmq-c versions, aren't we?
