### ISSUE TITLE
Can not build on Mac OS X Yosemite (10.10.1) 

### ISSUE THREAD

**Issue by iwind** [pdezwart/php-amqp#141]
PHP 5.6
librabbitmq 0.5.2 (downloaded from github)
php-amqp 1.6.0 beta2 (From pecl.php.net or from github)

~~~
phpize .
./configure
make
~~~

then error occurs:

~~~
duplicate symbol _le_amqp_connection_resource_persistent in:
    .libs/amqp.o
    .libs/amqp_connection.o
duplicate symbol _le_amqp_connection_resource in:
    .libs/amqp.o
    .libs/amqp_connection.o
duplicate symbol _le_amqp_connection_resource in:
    .libs/amqp.o
    .libs/amqp_connection_resource.o
duplicate symbol _le_amqp_connection_resource_persistent in:
    .libs/amqp.o
    .libs/amqp_connection_resource.o
duplicate symbol _le_amqp_connection_resource in:
    .libs/amqp.o
    .libs/amqp_channel.o
duplicate symbol _le_amqp_connection_resource_persistent in:
    .libs/amqp.o
    .libs/amqp_channel.o
ld: 6 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [amqp.la] Error 1
~~~

**Comment by pinepain** [comment]
Confirmed. I will look what's wrong.

**Comment by pinepain** [comment]
Should be fixed in https://github.com/pdezwart/php-amqp/pull/142

**Comment by iwind** [comment]
Thank you, the issue has been fixed so quickly!
