### ISSUE TITLE
Failed build with librabbitmq 0.5

### ISSUE THREAD

**Issue by remicollet** [pdezwart/php-amqp#177]
1.6.0beta3 build fine with librabbitmq 0.5.x (available in EPEL for RHEL and CentOS, can't be upgrade because of ABI break)

Buildtime:

    /builddir/build/BUILD/more-php56-php-pecl-amqp-1.6.0/NTS/amqp_connection.c:146: warning: implicit declaration of function 'amqp_get_frame_max'
    /builddir/build/BUILD/more-php56-php-pecl-amqp-1.6.0/NTS/amqp_connection.c:154: warning: implicit declaration of function 'amqp_get_heartbeat'

Runtime:

     PHP Warning:  PHP Startup: Unable to load dynamic library 'NTS/modules/amqp.so' - NTS/modules/amqp.so: undefined symbol: amqp_get_heartbeat in Unknown on line 0

It will be nice to have this feature conditional.
If not possible, to check (in config.m4) with a message explaining minimal version required.
